### ISSUE TITLE
Set branch protection rule to 'main' branch

### ISSUE THREAD

**Issue by y1hongju** [dre4m1ng/spring-of-fifa#12]
`main` 브랜치를 보호하는 새로운 rule을 적용합니다. 아래는 각 rule과 간단한 설명입니다.

- Require a pull request before merging
  - main 브랜치로 직접 push 제한
  - 안전하게 pull request로만 코드 반영이 가능하도록 하기 위함
- Require review from Code Owners
  - 기존에 작성된 코드를 변경하는 경우 해당 코드를 작성한 코더에게 승인을 받아야 하는 옵션
- ~~Require linear history~~ 차후 적용하는 것으로 논의되었습니다.
  - ~~커밋 히스토리를 깔끔하게 관리하기 위한 방법~~
  - ~~크게 바뀌는 건 없고, pull request를 승인할 때 `rebase and merge` 옵션을 선택하는 방식 [공식문서 링크](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#rebase-and-merge-your-pull-request-commits)~~

rule 개념을 처음 보시는 분도 계실 것 같은데, 보시고 이해가 안 되는 것이 있으시면 편하게 코멘트 남겨주세용 :)

**Comment by MARKZZAM** [comment]
1번 2번 채낵 하였습니다.
